# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# using concurrency to manage multiple runs
name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
    paths:
      - "./web/src/**" # only runs this workflow if something change inside src directory
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.event.pull_request.number || github.ref || github.run_id}}
  cancel-in-progress: true

env:
  REGISTRY: "ghrc.io"
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write # Push to GHCR

jobs:
  #linting and check packages vulnerability
  lint:
    name: "Run Linter"
    defaults:
      run:
        shell: bash
        working-directory: ./web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: "Checkout repository"

      - name: "Setup nodejs"
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: ./web/package-lock.json

      - name: "Install Dependencies"
        run: npm ci

      - name: "Run lint"
        run: npm run lint

      - name: "Security audit"
        run: npm audit --omit=dev --audit-level=high

  # start testing
  test:
    name: "Run Test"
    needs: [lint]
    defaults:
      run:
        shell: bash
        working-directory: ./web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: "Checkout repository"

      - name: "Setup nodejs"
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: ./web/package-lock.json

      - name: "Install Dependencies"
        run: npm ci

      - name: "Run Test"
        run: npm run test

  #start building
  build-and-push:
    name: "build and push docker image"
    needs: [lint, test]
    defaults:
      run:
        shell: bash
        working-directory: ./web
    runs-on: ubuntu-

    outputs:
      image-digest: ${{ steps.build.outputs.digest}}
      image-tags: ${{steps.meta.outputs.tags}}

    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3

        # build cross platform builds doesn't matter in whcih operating you making build
      - name: "set up QEMU"
        uses: docker/setup-qemu-actions@v3

      - name: "setup docker build"
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:latest

      - name: "login to the github container registry"
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title='cicd backend'

      - name: "Build and push docker image"
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ./web
          platforms: linux/amd64 , linux/arm64
          push: ${{ github.event_name != 'pull_request' }}

          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

          # before building try to restore docker layers form github actions cache
          cache-from: type=gha
          # after building save all docker layers to github actions cache
          cache-to: type=gha , mode=max
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }} 
            VCS_REF=${{ github.sha }}
          #how and who built it
          provenance: true
          # what inside of image they were save as oci artifact and linked to the images
          sbom: true

  # Security Scanning after build and push
  security-scan:
    name: "Run Trivy vulnerability scanner"
    needs: [build-and-push]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./web
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY}}/${{env.IMAGE_NAME}}@${{steps.build.outputs.digest}}
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL , HIGH"

      - name: Upload Trivuy-security file to gitub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
