# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# using concurrency to manage multiple runs
name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
    paths:
      - "./web/src/**" # only runs this workflow if something change inside src directory
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.event.pull_request.number || github.ref || github.run_id}}
  cancel-in-progress: true

jobs:
  lint:
    name: "Run Linter"
    defaults:
      run:
        shell: bash
        working-directory: ./web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: "Checkout repository"

      - name: "Setup nodejs"
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: ./web/package-lock.json

      - name: "Install Dependencies"
        run: npm ci

      - name: "Run lint"
        run: npm run lint

  test:
    name: "Run Test"
    needs: [lint]
    defaults:
      run:
        shell: bash
        working-directory: ./web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: "Checkout repository"

      - name: "Setup nodejs"
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: ./web/package-lock.json

      - name: "Install Dependencies"
        run: npm ci

      - name: "Run Test"
        run: npm run test

  build:
    name: "Run Build"
    needs: [lint, test]
    defaults:
      run:
        shell: bash
        working-directory: ./web
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout repository"'
        uses: actions/checkout@v3

      - name: "Setup nodejs"
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: ./web/package-lock.json

      - name: "install Dependencies"
        run: npm ci

      - name: "make build"
        run: npm run build

      - name: "Upload Build Artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./web/dist/
  # Copy only dist/, package.json, node_modules (production)
